-- =====================================================================
-- Vesta: complete database setup. Paste this whole file into the
-- Supabase SQL editor and press Run. It is safe to run once, and safe
-- to run again after a new migration is added.
--
-- Generated by cloud/setup/build_sql.py. Do not edit by hand: edit the
-- files in cloud/supabase/ and regenerate.
--
-- It grants every role explicitly, so it does not depend on Supabase's
-- "Automatically expose new tables" setting being on or off.
-- =====================================================================



-- =====================================================================
-- 001_schema.sql
-- =====================================================================

-- Vesta cloud schema
-- Run this once against a fresh Supabase project (SQL Editor, or `supabase db push`).
--
-- Design rules this file follows, so future migrations stay consistent:
--
--  1. EVERY user table carries `user_id uuid not null default auth.uid()`.
--     Denormalising the owner onto child rows (subtasks, schedule entries) instead of
--     joining up to the parent keeps every Row Level Security policy a single indexed
--     equality check. It is the pattern Supabase recommends and it stays fast.
--  2. IDs are uuid and are supplied by the client where useful. The existing local
--     SQLite data already uses uuid4 strings, so the migration preserves every id and
--     nothing that references an id has to be rewritten.
--  3. Deletes cascade from the owner down. Removing an auth user removes their world.
--  4. Soft delete (`deleted_at`) is only on the things the user asked to be able to
--     recover: notes and files. Everything else deletes for real.
--  5. Timestamps are timestamptz, always. Dates that mean "a calendar day with no
--     timezone" (a due date, a term start) stay `date`.

-- gen_random_uuid() has been part of core PostgreSQL since 13, so pgcrypto is
-- only needed on older servers. Supabase already has it. Tolerate its absence so
-- this file also runs against a plain Postgres for testing.
do $$
begin
  create extension if not exists "pgcrypto";
exception when others then
  raise notice 'pgcrypto unavailable (%); continuing, gen_random_uuid() is core in PG13+.', sqlerrm;
end;
$$;

-- ---------------------------------------------------------------------------
-- profiles: the app's own row per auth user
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  email        text,
  display_name text,
  avatar_url   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- allowed_emails: signup is invite-only, so a stranger cannot create an account
-- and start consuming storage.
--
-- This is an email allowlist rather than a redeemable invite code on purpose.
-- A code has to be carried through the signup request, and the Google OAuth
-- round trip gives us nowhere reliable to put one. An email is present on every
-- new user no matter which provider they came in through, so one check covers
-- Google sign-in and email/password identically.
--
-- Add people by hand:  insert into allowed_emails (email) values ('friend@x.com');
-- ---------------------------------------------------------------------------
create table if not exists allowed_emails (
  email      text primary key,
  note       text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- semesters: replaces the old single-row term_settings
-- ---------------------------------------------------------------------------
create table if not exists semesters (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name       text not null default '',
  start_date date,
  end_date   date,
  is_active  boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists semesters_user_idx on semesters(user_id);
-- at most one active semester per user
create unique index if not exists semesters_one_active_idx
  on semesters(user_id) where is_active;

-- ---------------------------------------------------------------------------
-- classes
-- ---------------------------------------------------------------------------
create table if not exists classes (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  semester_id uuid references semesters(id) on delete set null,
  code        text not null default '',
  name        text not null default '',
  professor   text not null default '',
  color       text not null default '#3576D9',
  notes       text not null default '',
  website     text not null default '',
  grade_scale jsonb,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists classes_user_idx     on classes(user_id);
create index if not exists classes_semester_idx on classes(semester_id);

create table if not exists schedule_entries (
  id       uuid primary key default gen_random_uuid(),
  user_id  uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id uuid not null references classes(id) on delete cascade,
  day      smallint not null check (day between 0 and 6),   -- 0 = Sunday
  start_time text,
  end_time   text,
  location   text not null default ''
);
create index if not exists schedule_user_idx  on schedule_entries(user_id);
create index if not exists schedule_class_idx on schedule_entries(class_id);

-- ---------------------------------------------------------------------------
-- items: assignments, exams, quizzes, readings
-- ---------------------------------------------------------------------------
create table if not exists items (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id      uuid references classes(id) on delete cascade,
  title         text not null default '',
  type          text not null default 'assignment'
                check (type in ('assignment','homework','quiz','exam','reading','discussion','project','other')),
  due_date      date,
  due_time      text,
  status        text not null default 'todo'
                check (status in ('todo','in_progress','done')),
  completed_at  date,
  weight        numeric,
  score         numeric,
  notes         text not null default '',
  focus_seconds integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists items_user_idx  on items(user_id);
create index if not exists items_class_idx on items(class_id);
create index if not exists items_due_idx   on items(user_id, due_date);

create table if not exists subtasks (
  id      uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  item_id uuid not null references items(id) on delete cascade,
  title   text not null default '',
  done    boolean not null default false,
  sort_order integer not null default 0
);
create index if not exists subtasks_user_idx on subtasks(user_id);
create index if not exists subtasks_item_idx on subtasks(item_id);

-- ---------------------------------------------------------------------------
-- calendar events that are not tied to an item (office hours, study groups)
-- ---------------------------------------------------------------------------
create table if not exists events (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id   uuid references classes(id) on delete cascade,
  title      text not null default '',
  kind       text not null default 'other',
  date       date not null,
  start_time text,
  end_time   text,
  all_day    boolean not null default false,
  location   text not null default '',
  notes      text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists events_user_idx on events(user_id);
create index if not exists events_date_idx on events(user_id, date);

-- ---------------------------------------------------------------------------
-- notes, their folders, their version history
-- ---------------------------------------------------------------------------
create table if not exists note_folders (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id   uuid references classes(id) on delete cascade,
  name       text not null default 'Untitled folder',
  created_at timestamptz not null default now()
);
create index if not exists note_folders_user_idx  on note_folders(user_id);
create index if not exists note_folders_class_idx on note_folders(class_id);

create table if not exists notes (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id       uuid references classes(id) on delete cascade,
  folder_id      uuid references note_folders(id) on delete set null,
  linked_item_id uuid references items(id) on delete set null,
  title          text not null default '',
  body           text not null default '',      -- HTML from the rich text editor
  -- Monotonic counter the client bumps on every save. Lets an offline device
  -- detect that the server moved on while it was away, instead of blindly
  -- overwriting a newer copy written from another device.
  revision       bigint not null default 1,
  deleted_at     timestamptz,                   -- 30-day Trash
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists notes_user_idx    on notes(user_id);
create index if not exists notes_class_idx   on notes(class_id);
create index if not exists notes_folder_idx  on notes(folder_id);
create index if not exists notes_live_idx    on notes(user_id) where deleted_at is null;
create index if not exists notes_trash_idx   on notes(user_id, deleted_at) where deleted_at is not null;

-- One row per saved version. Written by a trigger, not by the client, so history
-- cannot be forged or skipped.
create table if not exists note_versions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  note_id    uuid not null references notes(id) on delete cascade,
  revision   bigint not null,
  title      text not null default '',
  body       text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists note_versions_note_idx on note_versions(note_id, created_at desc);
create index if not exists note_versions_user_idx on note_versions(user_id);

-- ---------------------------------------------------------------------------
-- syllabus topics
-- ---------------------------------------------------------------------------
create table if not exists syllabus_topics (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id   uuid not null references classes(id) on delete cascade,
  title      text not null default '',
  done       boolean not null default false,
  sort_order integer not null default 0
);
create index if not exists syllabus_user_idx  on syllabus_topics(user_id);
create index if not exists syllabus_class_idx on syllabus_topics(class_id);

-- ---------------------------------------------------------------------------
-- files: one row per distinct uploaded blob in R2.
--
-- The blob is stored ONCE. Where it shows up in the app is decided entirely by
-- rows in `attachments`, so the same PDF linked to a class, an assignment and a
-- note costs one object in R2 and one row here.
--
-- `status` is the upload state machine. A row is created as 'pending' before the
-- browser starts pushing bytes to R2, and is only flipped to 'complete' once the
-- upload is confirmed. Anything left 'pending' is an abandoned upload and is safe
-- to sweep.
-- ---------------------------------------------------------------------------
create table if not exists files (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null default auth.uid() references auth.users(id) on delete cascade,
  r2_key         text not null,
  sha256         text,                 -- content hash, used to dedupe within one user
  filename       text not null default '',
  mimetype       text not null default 'application/octet-stream',
  size_bytes     bigint not null default 0,
  status         text not null default 'pending'
                 check (status in ('pending','uploading','complete','failed')),
  upload_id      text,                 -- R2 multipart upload id, for resumable large files
  bytes_received bigint not null default 0,
  extracted_text text,                 -- filled in for PDF/DOCX so Headstart can read them
  -- The UI only ever asks whether text was extracted, never for the text itself.
  -- Exposing it as a column keeps the extracted body (which can be 200 KB) out of
  -- the payload every time the file list loads.
  has_text boolean generated always as (extracted_text is not null) stored,
  deleted_at     timestamptz,          -- 30-day Trash
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create unique index if not exists files_r2_key_idx on files(r2_key);
-- the dedupe key: same user, same bytes, one row
create unique index if not exists files_user_sha_idx
  on files(user_id, sha256) where sha256 is not null and deleted_at is null;
create index if not exists files_user_idx   on files(user_id);
create index if not exists files_status_idx on files(user_id, status);

-- ---------------------------------------------------------------------------
-- attachments: "this resource appears in this place".
--
-- Replaces the old `materials` table. Exactly one target column is set, which
-- Postgres enforces below, so deletes cascade correctly and there is no
-- polymorphic target_id that the database cannot check.
--
-- An attachment is either a stored file (file_id set) or an external bookmark
-- (url set), never both.
-- ---------------------------------------------------------------------------
create table if not exists attachments (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  file_id     uuid references files(id) on delete cascade,
  url         text,
  title       text not null default '',
  category    text not null default 'other'
              check (category in ('syllabus','slides','readings','rubrics','exams','projects','personal','other')),
  class_id     uuid references classes(id) on delete cascade,
  item_id      uuid references items(id) on delete cascade,
  note_id      uuid references notes(id) on delete cascade,
  headstart_id uuid,   -- FK added after headstarts is created, below
  starred     boolean not null default false,
  created_at  timestamptz not null default now(),
  constraint attachments_is_file_or_link check (
    (file_id is not null and url is null) or
    (file_id is null and url is not null)
  ),
  constraint attachments_exactly_one_target check (
    (case when class_id     is not null then 1 else 0 end) +
    (case when item_id      is not null then 1 else 0 end) +
    (case when note_id      is not null then 1 else 0 end) +
    (case when headstart_id is not null then 1 else 0 end) = 1
  )
);
create index if not exists attachments_user_idx  on attachments(user_id);
create index if not exists attachments_file_idx  on attachments(file_id);
create index if not exists attachments_class_idx on attachments(class_id);
create index if not exists attachments_item_idx  on attachments(item_id);
create index if not exists attachments_note_idx  on attachments(note_id);

-- ---------------------------------------------------------------------------
-- Headstart: AI-generated drafts, outlines and study prep, per item
-- ---------------------------------------------------------------------------
create table if not exists headstarts (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  item_id      uuid not null references items(id) on delete cascade,
  kind         text not null
               check (kind in ('draft','essay_outline','quiz_prep','study_outline','synthesis','explain')),
  content      text not null default '',
  status       text not null default 'draft'
               check (status in ('draft','generating','ready','error')),
  instructions text not null default '',
  model        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (item_id, kind)
);
create index if not exists headstarts_user_idx on headstarts(user_id);
create index if not exists headstarts_item_idx on headstarts(item_id);

alter table attachments
  drop constraint if exists attachments_headstart_id_fkey;
alter table attachments
  add constraint attachments_headstart_id_fkey
  foreign key (headstart_id) references headstarts(id) on delete cascade;

-- ---------------------------------------------------------------------------
-- rubrics, parsed out of an uploaded rubric file
-- ---------------------------------------------------------------------------
create table if not exists rubrics (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  file_id      uuid references files(id) on delete cascade,
  item_id      uuid references items(id) on delete set null,
  criteria     jsonb not null default '[]'::jsonb,
  total_points numeric,
  created_at   timestamptz not null default now()
);
create index if not exists rubrics_user_idx on rubrics(user_id);
create index if not exists rubrics_item_idx on rubrics(item_id);
create unique index if not exists rubrics_file_idx on rubrics(file_id) where file_id is not null;

-- ---------------------------------------------------------------------------
-- focus sessions: real measured study time, not wall clock since Start.
-- The local app already counts only ticked seconds; this is where they land so
-- the history survives a device change.
-- ---------------------------------------------------------------------------
create table if not exists focus_sessions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
  item_id    uuid references items(id) on delete set null,
  class_id   uuid references classes(id) on delete set null,
  seconds    integer not null default 0,
  started_at timestamptz not null default now(),
  ended_at   timestamptz,
  day        date not null default (now() at time zone 'utc')::date
);
create index if not exists focus_user_day_idx on focus_sessions(user_id, day);
create index if not exists focus_item_idx     on focus_sessions(item_id);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
create or replace function touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'profiles','semesters','classes','items','events','notes','files','headstarts'
  ] loop
    execute format('drop trigger if exists %I_touch on %I', t, t);
    execute format(
      'create trigger %I_touch before update on %I
       for each row execute function touch_updated_at()', t, t);
  end loop;
end;
$$;


-- =====================================================================
-- 002_rls.sql
-- =====================================================================

-- Vesta Row Level Security
--
-- This file IS the security model. The browser talks to Postgres directly through
-- PostgREST using the anon key, which is public by design and safe to ship in the
-- page. Nothing stops a user from crafting their own query. What stops them from
-- reading someone else's classes is the policies below, and nothing else.
--
-- The rules:
--   * RLS is ON for every table. A table with RLS on and no policy denies everyone.
--   * Ownership is always `user_id = auth.uid()`. auth.uid() reads the caller's JWT,
--     so it cannot be spoofed from the client.
--   * Every policy pair uses USING for the rows you may see or change, and WITH CHECK
--     for the rows you may leave behind. Omitting WITH CHECK on an update would let a
--     user hand their row to someone else, or claim someone else's.
--   * The service role key bypasses all of this. It lives only in the Cloudflare
--     Worker's secrets and must never reach the browser.

-- ---------------------------------------------------------------------------
-- helper: apply the standard owner-only policy set to a table
-- ---------------------------------------------------------------------------
create or replace function apply_owner_rls(tbl text)
returns void
language plpgsql
as $$
begin
  execute format('alter table %I enable row level security', tbl);
  execute format('alter table %I force row level security', tbl);

  execute format('drop policy if exists %I on %I', tbl || '_select_own', tbl);
  execute format('drop policy if exists %I on %I', tbl || '_insert_own', tbl);
  execute format('drop policy if exists %I on %I', tbl || '_update_own', tbl);
  execute format('drop policy if exists %I on %I', tbl || '_delete_own', tbl);

  execute format(
    'create policy %I on %I for select to authenticated using (user_id = auth.uid())',
    tbl || '_select_own', tbl);

  execute format(
    'create policy %I on %I for insert to authenticated with check (user_id = auth.uid())',
    tbl || '_insert_own', tbl);

  -- USING decides which rows may be updated, WITH CHECK decides what they may
  -- become. Both are required: without WITH CHECK a user could reassign user_id.
  execute format(
    'create policy %I on %I for update to authenticated
       using (user_id = auth.uid()) with check (user_id = auth.uid())',
    tbl || '_update_own', tbl);

  execute format(
    'create policy %I on %I for delete to authenticated using (user_id = auth.uid())',
    tbl || '_delete_own', tbl);
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'semesters',
    'classes',
    'schedule_entries',
    'items',
    'subtasks',
    'events',
    'note_folders',
    'notes',
    'syllabus_topics',
    'files',
    'attachments',
    'headstarts',
    'rubrics',
    'focus_sessions'
  ] loop
    perform apply_owner_rls(t);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- profiles: keyed by the auth user id itself, not a user_id column
-- ---------------------------------------------------------------------------
alter table profiles enable row level security;
alter table profiles force row level security;

drop policy if exists profiles_select_own on profiles;
drop policy if exists profiles_update_own on profiles;
drop policy if exists profiles_insert_own on profiles;

create policy profiles_select_own on profiles
  for select to authenticated using (id = auth.uid());
create policy profiles_insert_own on profiles
  for insert to authenticated with check (id = auth.uid());
create policy profiles_update_own on profiles
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
-- deliberately no delete policy: a profile goes away with its auth user, not on demand

-- ---------------------------------------------------------------------------
-- note_versions: readable and deletable by the owner, but never written by the
-- client. Rows appear only via the trigger in 003, which runs as definer.
-- ---------------------------------------------------------------------------
alter table note_versions enable row level security;
alter table note_versions force row level security;

drop policy if exists note_versions_select_own on note_versions;
drop policy if exists note_versions_delete_own on note_versions;

create policy note_versions_select_own on note_versions
  for select to authenticated using (user_id = auth.uid());
create policy note_versions_delete_own on note_versions
  for delete to authenticated using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- allowed_emails: RLS on, zero policies. That denies every client outright,
-- including reads. Only the signup trigger (security definer) and the service
-- role can see it, so nobody can enumerate who is allowed in.
-- ---------------------------------------------------------------------------
alter table allowed_emails enable row level security;
alter table allowed_emails force row level security;

-- ---------------------------------------------------------------------------
-- Table privileges.
--
-- These are a different mechanism from RLS and both must be right. GRANT decides
-- whether a role may attempt an operation on a table at all; RLS then decides
-- which rows it sees. Supabase's default privileges normally cover new tables in
-- public, but stating it explicitly keeps this file self-contained.
--
-- `anon` is the role for a visitor with no session. Vesta has nothing an anonymous
-- visitor should read, so anon is granted nothing at all.
-- ---------------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- The Cloudflare Worker connects as service_role. It bypasses RLS, but bypassing
-- RLS is not the same as being allowed to touch the table at all, so it still
-- needs these grants. Without them file uploads fail with "permission denied",
-- and only Supabase's "automatically expose new tables" default privileges would
-- have been quietly covering for it.
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on all tables in schema public from anon;

-- allowed_emails is invisible to every client role. RLS already denies it, this
-- makes it a permission error rather than an empty result, and stops anyone
-- enumerating who has been invited.
revoke all on allowed_emails from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Sanity check. Run this any time; it must return zero rows.
-- Any table listed here is a table the browser can read without restriction.
-- ---------------------------------------------------------------------------
-- select c.relname as table_without_rls
-- from pg_class c
-- join pg_namespace n on n.oid = c.relnamespace
-- where n.nspname = 'public'
--   and c.relkind = 'r'
--   and c.relrowsecurity = false;


-- =====================================================================
-- 003_functions.sql
-- =====================================================================

-- Vesta triggers, retention and housekeeping.

-- ---------------------------------------------------------------------------
-- Signup gate + profile creation.
--
-- Runs on every new auth user regardless of provider, so it covers Google
-- sign-in and email/password with one check. Raising here aborts the signup
-- transaction, so a rejected email never becomes an account at all.
-- ---------------------------------------------------------------------------
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.email is null
     or not exists (
       select 1 from allowed_emails
       where lower(allowed_emails.email) = lower(new.email)
     )
  then
    raise exception 'This email has not been invited to Vesta.'
      using errcode = '42501';
  end if;

  insert into profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      split_part(new.email, '@', 1)
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;

  -- Give every new account one semester so the app has somewhere to put classes.
  insert into semesters (user_id, name, is_active)
  values (new.id, 'Current term', true);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ---------------------------------------------------------------------------
-- Note version history.
--
-- Autosave fires roughly once a second while typing, so snapshotting on every
-- write would put thousands of near-identical rows in a 500 MB database. This
-- keeps at most one version per note per 5 minutes of editing, and prunes each
-- note to its 50 most recent versions. That is enough to walk back a bad edit
-- without the history becoming the largest thing in the database.
-- ---------------------------------------------------------------------------
create or replace function snapshot_note_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  last_version_at timestamptz;
begin
  -- nothing to snapshot if the text did not actually change
  if new.body is not distinct from old.body
     and new.title is not distinct from old.title then
    return new;
  end if;

  select max(created_at) into last_version_at
  from note_versions where note_id = old.id;

  if last_version_at is null or last_version_at < now() - interval '5 minutes' then
    insert into note_versions (user_id, note_id, revision, title, body)
    values (old.user_id, old.id, old.revision, old.title, old.body);

    delete from note_versions
    where note_id = old.id
      and id not in (
        select id from note_versions
        where note_id = old.id
        order by created_at desc
        limit 50
      );
  end if;

  return new;
end;
$$;

drop trigger if exists notes_snapshot on notes;
create trigger notes_snapshot
  before update on notes
  for each row execute function snapshot_note_version();

-- ---------------------------------------------------------------------------
-- R2 cleanup queue.
--
-- Deleting a file row would throw away the r2_key with it, and the object would
-- sit in the bucket forever costing storage. So the key is copied here first and
-- the Cloudflare Worker's scheduled job drains the queue and deletes the objects.
-- ---------------------------------------------------------------------------
create table if not exists r2_deletion_queue (
  id           uuid primary key default gen_random_uuid(),
  r2_key       text not null,
  queued_at    timestamptz not null default now(),
  attempts     integer not null default 0,
  last_error   text,
  deleted_at   timestamptz
);
create index if not exists r2_queue_pending_idx
  on r2_deletion_queue(queued_at) where deleted_at is null;

alter table r2_deletion_queue enable row level security;
alter table r2_deletion_queue force row level security;
-- No policies, so RLS denies every client. The revoke is belt and braces: this
-- table is created after 002 ran, so Supabase's default privileges would
-- otherwise have granted it to anon and authenticated.
revoke all on r2_deletion_queue from anon, authenticated;
-- 002's blanket grant ran before this table existed, so the Worker needs its own.
grant select, insert, update, delete on r2_deletion_queue to service_role;

create or replace function queue_r2_delete()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.r2_key is not null and old.r2_key <> '' then
    insert into r2_deletion_queue (r2_key) values (old.r2_key);
  end if;
  return old;
end;
$$;

drop trigger if exists files_queue_r2_delete on files;
create trigger files_queue_r2_delete
  before delete on files
  for each row execute function queue_r2_delete();

-- ---------------------------------------------------------------------------
-- Retention: empty the 30-day Trash, and sweep uploads that never finished.
--
-- Called by pg_cron below. Safe to run by hand at any time.
-- ---------------------------------------------------------------------------
create or replace function run_vesta_retention()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- 30-day Trash for notes
  delete from notes
  where deleted_at is not null
    and deleted_at < now() - interval '30 days';

  -- 30-day Trash for files. The delete trigger queues each r2_key for the Worker.
  delete from files
  where deleted_at is not null
    and deleted_at < now() - interval '30 days';

  -- An upload that never reported completion within a day is abandoned. Removing
  -- the row also queues whatever partial object exists in R2 for deletion.
  delete from files
  where status in ('pending', 'uploading')
    and created_at < now() - interval '1 day';

  -- Versions of notes that no longer exist cannot happen (FK cascades), but
  -- history for a note that has been in the trash the whole time is dead weight.
  delete from note_versions v
  using notes n
  where v.note_id = n.id
    and n.deleted_at is not null
    and n.deleted_at < now() - interval '7 days';
end;
$$;

-- ---------------------------------------------------------------------------
-- Schedule it. pg_cron is available on Supabase including the free tier, but it
-- has to be enabled once. If this block reports a notice instead of scheduling,
-- turn on `pg_cron` under Database -> Extensions and re-run the file.
-- ---------------------------------------------------------------------------
do $$
begin
  create extension if not exists pg_cron;

  perform cron.unschedule('vesta-retention')
  where exists (select 1 from cron.job where jobname = 'vesta-retention');

  perform cron.schedule(
    'vesta-retention',
    '17 4 * * *',                  -- 04:17 UTC daily, off-peak
    $job$ select run_vesta_retention(); $job$
  );
exception when others then
  raise notice 'pg_cron not scheduled (%). Enable the pg_cron extension and re-run 003_functions.sql.', sqlerrm;
end;
$$;


-- =====================================================================
-- 004_study.sql
-- =====================================================================

-- Vesta: grade categories, flashcards and quizzes.
--
-- Runs after 002, because it calls apply_owner_rls() which that file defines.
--
-- Nothing here has a screen yet. The point is that the shape of the data is
-- settled before features are built on top of it, so adding the study tools later
-- does not mean a migration that touches everything.

-- ---------------------------------------------------------------------------
-- grade_categories
--
-- Grades were previously computed from a weight on each assignment. That works
-- until a syllabus says "Assignments 40%, Midterm 25%, Final 35%", which is how
-- courses are actually graded. A category holds the weight, assignments belong to
-- a category, and an assignment's own weight becomes its share within it.
--
-- `drop_lowest` handles the common "we drop your worst quiz" rule.
-- ---------------------------------------------------------------------------
create table if not exists grade_categories (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id    uuid not null references classes(id) on delete cascade,
  name        text not null default '',
  weight      numeric not null default 0,      -- percent of the final grade
  drop_lowest integer not null default 0,      -- how many lowest scores to ignore
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);
create index if not exists grade_categories_user_idx  on grade_categories(user_id);
create index if not exists grade_categories_class_idx on grade_categories(class_id);

-- Assignments can now sit in a category. Nullable, so everything that already
-- exists keeps working exactly as it does today.
alter table items add column if not exists category_id uuid
  references grade_categories(id) on delete set null;
create index if not exists items_category_idx on items(category_id);

-- ---------------------------------------------------------------------------
-- flashcards
--
-- Scheduling fields follow the SM-2 family: each card carries its own ease and
-- interval, and `due_date` is what a study session queries. Keeping the schedule
-- on the card rather than in a separate review log means "what do I study today"
-- is one indexed lookup.
-- ---------------------------------------------------------------------------
create table if not exists flashcard_decks (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id    uuid references classes(id) on delete cascade,
  name        text not null default 'Untitled deck',
  description text not null default '',
  -- where the deck came from, when it was generated rather than typed
  source_note_id uuid references notes(id) on delete set null,
  source_file_id uuid references files(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists decks_user_idx  on flashcard_decks(user_id);
create index if not exists decks_class_idx on flashcard_decks(class_id);

create table if not exists flashcards (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null default auth.uid() references auth.users(id) on delete cascade,
  deck_id          uuid not null references flashcard_decks(id) on delete cascade,
  front            text not null default '',
  back             text not null default '',
  -- spaced repetition state
  ease             numeric not null default 2.5,   -- SM-2 ease factor
  interval_days    integer not null default 0,
  repetitions      integer not null default 0,
  lapses           integer not null default 0,
  due_date         date not null default (now() at time zone 'utc')::date,
  last_reviewed_at timestamptz,
  suspended        boolean not null default false,
  sort_order       integer not null default 0,
  created_at       timestamptz not null default now()
);
create index if not exists flashcards_user_idx on flashcards(user_id);
create index if not exists flashcards_deck_idx on flashcards(deck_id);
-- the query a study session actually runs
create index if not exists flashcards_due_idx
  on flashcards(user_id, due_date) where not suspended;

-- ---------------------------------------------------------------------------
-- quizzes
--
-- Questions are rows rather than a blob on the quiz, so a single question can be
-- edited, reordered or reported on. Answers to an attempt stay as jsonb, because
-- they are only ever read back as a whole.
-- ---------------------------------------------------------------------------
create table if not exists quizzes (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  class_id    uuid references classes(id) on delete cascade,
  item_id     uuid references items(id) on delete set null,   -- the exam it prepares for
  title       text not null default 'Untitled quiz',
  source      text not null default 'manual'
              check (source in ('manual','headstart','file','note')),
  source_file_id uuid references files(id) on delete set null,
  source_note_id uuid references notes(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists quizzes_user_idx  on quizzes(user_id);
create index if not exists quizzes_class_idx on quizzes(class_id);

create table if not exists quiz_questions (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  quiz_id     uuid not null references quizzes(id) on delete cascade,
  kind        text not null default 'multiple_choice'
              check (kind in ('multiple_choice','true_false','short_answer')),
  prompt      text not null default '',
  choices     jsonb not null default '[]'::jsonb,   -- ["A","B","C","D"] for multiple choice
  answer      text not null default '',
  explanation text not null default '',
  sort_order  integer not null default 0
);
create index if not exists quiz_questions_user_idx on quiz_questions(user_id);
create index if not exists quiz_questions_quiz_idx on quiz_questions(quiz_id, sort_order);

create table if not exists quiz_attempts (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  quiz_id      uuid not null references quizzes(id) on delete cascade,
  responses    jsonb not null default '{}'::jsonb,  -- { question_id: given_answer }
  score        numeric,                             -- percent correct
  correct_count integer not null default 0,
  total_count   integer not null default 0,
  started_at   timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists quiz_attempts_user_idx on quiz_attempts(user_id);
create index if not exists quiz_attempts_quiz_idx on quiz_attempts(quiz_id, started_at desc);

-- ---------------------------------------------------------------------------
-- Same owner-only rules as everything else, and the same explicit grants, so
-- these tables do not depend on Supabase's "expose new tables" setting either.
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'grade_categories',
    'flashcard_decks',
    'flashcards',
    'quizzes',
    'quiz_questions',
    'quiz_attempts'
  ] loop
    perform apply_owner_rls(t);
  end loop;
end;
$$;

grant select, insert, update, delete on
  grade_categories, flashcard_decks, flashcards, quizzes, quiz_questions, quiz_attempts
  to authenticated, service_role;

-- keep updated_at honest on the two tables that have it
do $$
declare t text;
begin
  foreach t in array array['flashcard_decks','quizzes'] loop
    execute format('drop trigger if exists %I_touch on %I', t, t);
    execute format(
      'create trigger %I_touch before update on %I
       for each row execute function touch_updated_at()', t, t);
  end loop;
end;
$$;


-- =====================================================================
-- 005_lockdown.sql
-- =====================================================================

-- Vesta: stop the database exposing its own functions as public endpoints.
--
-- Found by probing the live project with nothing but the public anon key:
--
--   GET /rest/v1/rpc/run_vesta_retention  ->  405, not 404
--
-- A 405 means "wrong method", which means the endpoint exists. PostgREST publishes
-- every function in the `public` schema that the caller may execute, and Postgres
-- grants EXECUTE on new functions to PUBLIC by default. So the retention job was
-- callable by anyone who opened the app, or who read the anon key out of the page,
-- which is exactly what the anon key is designed to allow.
--
-- run_vesta_retention() is SECURITY DEFINER, so it runs with the owner's rights and
-- ignores Row Level Security. Calling it does not read anyone's data, but it does
-- delete: notes and files whose 30 days in the Trash are up, and uploads that never
-- finished. An anonymous caller could therefore cut short the recovery window a
-- user was promised. That is small, but it is real, and it is not something a
-- stranger should be able to trigger.
--
-- Nothing in Vesta calls an RPC from the browser: the app talks to tables, and the
-- Worker uses the service role. So the correct setting is that client roles may
-- execute nothing at all, and any future function is closed unless deliberately
-- opened.

-- Existing functions: close them to both client roles.
revoke execute on all functions in schema public from anon, authenticated;
revoke execute on all functions in schema public from public;

-- Future functions: closed by default, so this cannot silently regress the next
-- time a migration adds one.
--
-- PUBLIC has to be named explicitly. Postgres grants EXECUTE on every new function
-- to PUBLIC, and anon and authenticated inherit through it, so revoking from those
-- two roles alone leaves the function reachable. Caught by the migration 006 test,
-- which found a new trigger function still callable after only the named revokes.
alter default privileges in schema public
  revoke execute on functions from public;
alter default privileges in schema public
  revoke execute on functions from anon, authenticated;

-- The Worker and the scheduler still need to work.
grant execute on all functions in schema public to service_role;

-- pg_cron runs run_vesta_retention() as the job owner, not as a client role, so
-- the nightly cleanup is unaffected by the revoke above.

-- ---------------------------------------------------------------------------
-- Check it. Both queries should return zero rows.
-- ---------------------------------------------------------------------------
-- Functions any client role can still execute:
--
-- select p.proname, r.rolname
-- from pg_proc p
-- join pg_namespace n on n.oid = p.pronamespace
-- cross join (values ('anon'),('authenticated')) as r(rolname)
-- where n.nspname = 'public'
--   and has_function_privilege(r.rolname, p.oid, 'EXECUTE');
--
-- Tables without Row Level Security:
--
-- select c.relname from pg_class c
-- join pg_namespace n on n.oid = c.relnamespace
-- where n.nspname = 'public' and c.relkind = 'r' and not c.relrowsecurity;


-- =====================================================================
-- 006_notes.sql
-- =====================================================================

-- Vesta: notes as a document system rather than a text box.
--
-- Adds nested folders with a type, note flags (pinned, starred, ordering),
-- links from a note to the things it is about, and full text search over the
-- note body.

-- ---------------------------------------------------------------------------
-- Folders: nested, typed, ordered.
--
-- `parent_id` is what turns a flat list into a tree. `kind` exists because the
-- common folders in a course are always the same four, and knowing which is
-- which lets the interface give them the right icon and sort them sensibly
-- without the user naming them precisely.
-- ---------------------------------------------------------------------------
alter table note_folders add column if not exists parent_id uuid
  references note_folders(id) on delete cascade;
alter table note_folders add column if not exists kind text not null default 'custom';
alter table note_folders add column if not exists sort_order integer not null default 0;

do $$
begin
  alter table note_folders drop constraint if exists note_folders_kind_check;
  alter table note_folders add constraint note_folders_kind_check
    check (kind in ('lecture','reading','exam','assignment','custom'));
end;
$$;

create index if not exists note_folders_parent_idx on note_folders(parent_id);

-- A folder cannot be inside itself, at any depth. Without this a single bad
-- drag makes the tree impossible to render and impossible to fix from the UI.
create or replace function check_folder_cycle()
returns trigger
language plpgsql
as $$
declare
  cursor_id uuid := new.parent_id;
  hops integer := 0;
begin
  if new.parent_id is null then
    return new;
  end if;
  if new.parent_id = new.id then
    raise exception 'A folder cannot be its own parent.';
  end if;
  while cursor_id is not null loop
    hops := hops + 1;
    if hops > 50 then
      raise exception 'Folder nesting is too deep.';
    end if;
    if cursor_id = new.id then
      raise exception 'That would put a folder inside one of its own subfolders.';
    end if;
    select parent_id into cursor_id from note_folders where id = cursor_id;
  end loop;
  return new;
end;
$$;

drop trigger if exists note_folders_no_cycles on note_folders;
create trigger note_folders_no_cycles
  before insert or update of parent_id on note_folders
  for each row execute function check_folder_cycle();

-- ---------------------------------------------------------------------------
-- Note flags
-- ---------------------------------------------------------------------------
alter table notes add column if not exists pinned     boolean not null default false;
alter table notes add column if not exists starred    boolean not null default false;
alter table notes add column if not exists sort_order integer not null default 0;
alter table notes add column if not exists icon       text;

create index if not exists notes_pinned_idx
  on notes(user_id) where pinned and deleted_at is null;
create index if not exists notes_starred_idx
  on notes(user_id) where starred and deleted_at is null;

-- ---------------------------------------------------------------------------
-- note_links: what a note is about.
--
-- `notes.linked_item_id` allowed exactly one assignment. A revision note for a
-- midterm realistically points at three lecture PDFs, a reading, the exam entry
-- on the calendar and the assignment itself, so this is a proper many-to-many.
--
-- Separate nullable foreign keys rather than a type/id pair, so Postgres can
-- actually enforce the reference and cascade the delete.
-- ---------------------------------------------------------------------------
create table if not exists note_links (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  note_id           uuid not null references notes(id) on delete cascade,
  item_id           uuid references items(id) on delete cascade,
  file_id           uuid references files(id) on delete cascade,
  event_id          uuid references events(id) on delete cascade,
  headstart_id      uuid references headstarts(id) on delete cascade,
  schedule_entry_id uuid references schedule_entries(id) on delete cascade,  -- a lecture
  target_note_id    uuid references notes(id) on delete cascade,
  label             text not null default '',
  created_at        timestamptz not null default now(),
  constraint note_links_one_target check (
    (case when item_id           is not null then 1 else 0 end) +
    (case when file_id           is not null then 1 else 0 end) +
    (case when event_id          is not null then 1 else 0 end) +
    (case when headstart_id      is not null then 1 else 0 end) +
    (case when schedule_entry_id is not null then 1 else 0 end) +
    (case when target_note_id    is not null then 1 else 0 end) = 1
  ),
  constraint note_links_no_self check (target_note_id is null or target_note_id <> note_id)
);
create index if not exists note_links_user_idx on note_links(user_id);
create index if not exists note_links_note_idx on note_links(note_id);
create index if not exists note_links_item_idx on note_links(item_id);
create index if not exists note_links_file_idx on note_links(file_id);

-- the same thing should not be attached to the same note twice
create unique index if not exists note_links_unique_idx
  on note_links(note_id,
                coalesce(item_id, '00000000-0000-0000-0000-000000000000'::uuid),
                coalesce(file_id, '00000000-0000-0000-0000-000000000000'::uuid),
                coalesce(event_id, '00000000-0000-0000-0000-000000000000'::uuid),
                coalesce(headstart_id, '00000000-0000-0000-0000-000000000000'::uuid),
                coalesce(schedule_entry_id, '00000000-0000-0000-0000-000000000000'::uuid),
                coalesce(target_note_id, '00000000-0000-0000-0000-000000000000'::uuid));

-- Carry the old single link across, then leave the column in place so nothing
-- that still reads it breaks. New links go in note_links.
insert into note_links (user_id, note_id, item_id)
select n.user_id, n.id, n.linked_item_id
from notes n
where n.linked_item_id is not null
on conflict do nothing;

-- ---------------------------------------------------------------------------
-- Search across titles and contents.
--
-- The body is HTML, so the tags are stripped before indexing, otherwise a search
-- for "table" would match every note containing one. Generated and stored, so the
-- index stays correct without the application remembering to update it.
-- ---------------------------------------------------------------------------
alter table notes add column if not exists search_tsv tsvector
  generated always as (
    to_tsvector('english',
      regexp_replace(coalesce(title, '') || ' ' || coalesce(body, ''), '<[^>]*>', ' ', 'g'))
  ) stored;

create index if not exists notes_search_idx on notes using gin (search_tsv);

-- ---------------------------------------------------------------------------
-- Same rules as every other table.
-- ---------------------------------------------------------------------------
do $$
begin
  perform apply_owner_rls('note_links');
end;
$$;

grant select, insert, update, delete on note_links to authenticated, service_role;

-- 005 revoked execute on every function from client roles; keep it that way for
-- the one added here. PUBLIC first: anon and authenticated inherit through it, so
-- revoking only the named roles would leave this callable.
revoke execute on function check_folder_cycle() from public;
revoke execute on function check_folder_cycle() from anon, authenticated;


-- =====================================================================
-- Invite list. Nobody can create an account unless their email is here.
-- Add friends later with another line just like this one.
-- =====================================================================
insert into allowed_emails (email, note) values
  ('saifabuhaltam@gmail.com', 'me')
on conflict (email) do nothing;


-- =====================================================================
-- Check it worked. Every row should show rls_enabled = true.
-- =====================================================================
select c.relname as table_name, c.relrowsecurity as rls_enabled
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relkind = 'r'
order by c.relname;
