#!/usr/bin/env python3
"""Concatenate the migrations into the single file you paste into Supabase.

    python3 cloud/setup/build_sql.py

Keeps cloud/setup/all_in_one.sql in step with cloud/supabase/*.sql so there is no
chance of pasting a stale copy.
"""
import glob
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "supabase")
OUT = os.path.join(HERE, "all_in_one.sql")

# Whoever runs this file is the first account. Everything imported later hangs off it.
OWNER_EMAIL = "saifabuhaltam@gmail.com"

HEADER = """-- =====================================================================
-- Vesta: complete database setup. Paste this whole file into the
-- Supabase SQL editor and press Run. It is safe to run once, and safe
-- to run again after a new migration is added.
--
-- Generated by cloud/setup/build_sql.py. Do not edit by hand: edit the
-- files in cloud/supabase/ and regenerate.
--
-- It grants every role explicitly, so it does not depend on Supabase's
-- "Automatically expose new tables" setting being on or off.
-- =====================================================================

"""

FOOTER = """

-- =====================================================================
-- Invite list. Nobody can create an account unless their email is here.
-- Add friends later with another line just like this one.
-- =====================================================================
insert into allowed_emails (email, note) values
  ('{owner}', 'me')
on conflict (email) do nothing;


-- =====================================================================
-- Check it worked. Every row should show rls_enabled = true.
-- =====================================================================
select c.relname as table_name, c.relrowsecurity as rls_enabled
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relkind = 'r'
order by c.relname;
"""


def main():
    files = sorted(glob.glob(os.path.join(SRC, "[0-9][0-9][0-9]_*.sql")))
    if not files:
        sys.exit(f"No migrations found in {SRC}")

    parts = [HEADER]
    for path in files:
        name = os.path.basename(path)
        parts.append(
            "\n\n-- =====================================================================\n"
            f"-- {name}\n"
            "-- =====================================================================\n\n"
        )
        parts.append(io.open(path, encoding="utf-8").read())
    parts.append(FOOTER.format(owner=OWNER_EMAIL))

    io.open(OUT, "w", encoding="utf-8").write("".join(parts))
    size = os.path.getsize(OUT)
    print(f"Wrote {OUT}")
    print(f"  {len(files)} migrations, {size // 1024} KB")
    for path in files:
        print(f"    {os.path.basename(path)}")
    print("\nCopy it with:  cat cloud/setup/all_in_one.sql | pbcopy")


if __name__ == "__main__":
    main()
