-- Vesta: Postgres schema, generated from the local SQLite database.
-- Source: /Users/saifabuhaltam/Developer/vesta/data/vesta.db
-- Generated by cloud/migrate/gen_pg_schema.py. Do not edit by hand.
--
-- Every table carries user_id default auth.uid() and forced owner-only RLS, so
-- the Flask app's existing queries need no user filtering: the database refuses
-- to return another student's rows even if a query forgets to ask.

begin;


-- ---------------------------------------------------------------------------
-- Identity. Supabase issues the tokens; this database only needs to know who a
-- request claims to be, and to have somewhere for rows to hang off so that
-- deleting an account takes its data with it.
-- ---------------------------------------------------------------------------
create schema if not exists auth;

create table if not exists auth.users (
  id         uuid primary key,
  email      text,
  created_at timestamptz not null default now()
);

-- Reads the caller's id out of the request-scoped claim the app sets on the
-- connection. It cannot be spoofed from SQL, because only the app sets it, and the
-- app sets it from a token whose signature it verified.
create or replace function auth.uid() returns uuid
language sql stable as $$
  select nullif(current_setting('request.jwt.claims', true)::json->>'sub', '')::uuid
$$;

do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'authenticated')
    then create role authenticated; end if;
  if not exists (select 1 from pg_roles where rolname = 'anon')
    then create role anon; end if;
end $$;

-- ---------------------------------------------------------------------------
-- The policy helper. Owner-only, forced, with WITH CHECK on updates so a row can
-- never be handed to another account.
-- ---------------------------------------------------------------------------
create or replace function apply_owner_rls(tbl text)
returns void language plpgsql as $$
begin
  execute format('alter table %I enable row level security', tbl);
  execute format('alter table %I force row level security', tbl);
  execute format('drop policy if exists %I on %I', tbl || '_select_own', tbl);
  execute format('drop policy if exists %I on %I', tbl || '_insert_own', tbl);
  execute format('drop policy if exists %I on %I', tbl || '_update_own', tbl);
  execute format('drop policy if exists %I on %I', tbl || '_delete_own', tbl);
  execute format(
    'create policy %I on %I for select to authenticated using (user_id = auth.uid())',
    tbl || '_select_own', tbl);
  execute format(
    'create policy %I on %I for insert to authenticated with check (user_id = auth.uid())',
    tbl || '_insert_own', tbl);
  execute format(
    'create policy %I on %I for update to authenticated
       using (user_id = auth.uid()) with check (user_id = auth.uid())',
    tbl || '_update_own', tbl);
  execute format(
    'create policy %I on %I for delete to authenticated using (user_id = auth.uid())',
    tbl || '_delete_own', tbl);
end;
$$;

-- ----------------------------------------------------------------------
create table if not exists ai_usage (
  "id" text,
  "kind" text,
  "model" text,
  "input_tokens" integer default 0,
  "output_tokens" integer default 0,
  "day" text,
  "created_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists ai_usage_user_idx on ai_usage(user_id);

-- ----------------------------------------------------------------------
create table if not exists app_settings (
  "key" text,
  "value" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key (user_id, "key")
);
create index if not exists app_settings_user_idx on app_settings(user_id);

-- ----------------------------------------------------------------------
create table if not exists calendar_accounts (
  "id" text,
  "provider" text,
  "name" text,
  "url" text,
  "calendar_id" text,
  "refresh_token" text,
  "access_token" text,
  "token_expires" text,
  "direction" text default 'both',
  "enabled" integer default 1,
  "sync_token" text,
  "last_sync" text,
  "last_error" text,
  "created_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists calendar_accounts_user_idx on calendar_accounts(user_id);

-- ----------------------------------------------------------------------
create table if not exists classes (
  "id" text,
  "code" text,
  "name" text,
  "professor" text,
  "color" text,
  "notes" text,
  "created_at" text,
  "grade_scale" text,
  "website" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists classes_user_idx on classes(user_id);

-- ----------------------------------------------------------------------
create table if not exists term_settings (
  "id" integer,
  "name" text,
  "start_date" text,
  "end_date" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key (user_id, "id")
);
create index if not exists term_settings_user_idx on term_settings(user_id);

-- ----------------------------------------------------------------------
create table if not exists calendar_imports (
  "id" text,
  "account_id" text references calendar_accounts("id") on delete set null,
  "class_id" text references classes("id") on delete cascade,
  "source" text,
  "label" text,
  "draft" text,
  "status" text default 'review',
  "created_at" text,
  "imported_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists calendar_imports_user_idx on calendar_imports(user_id);

-- ----------------------------------------------------------------------
create table if not exists events (
  "id" text,
  "class_id" text references classes("id") on delete cascade,
  "title" text,
  "kind" text,
  "date" text,
  "start" text,
  "end" text,
  "all_day" integer default 0,
  "location" text,
  "notes" text,
  "created_at" text,
  "source" text default 'vesta',
  "account_id" text,
  "external_id" text,
  "read_only" integer default 0,
  "updated_at" text,
  "deleted_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists events_user_idx on events(user_id);

-- ----------------------------------------------------------------------
create table if not exists grade_categories (
  "id" text,
  "class_id" text not null references classes("id") on delete cascade,
  "name" text,
  "weight" double precision,
  "drop_lowest" integer default 0,
  "sort_order" integer default 0,
  "created_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists grade_categories_user_idx on grade_categories(user_id);

-- ----------------------------------------------------------------------
create table if not exists items (
  "id" text,
  "class_id" text references classes("id") on delete cascade,
  "title" text,
  "type" text,
  "due_date" text,
  "due_time" text,
  "status" text,
  "completed_at" text,
  "weight" double precision,
  "score" double precision,
  "notes" text,
  "focus_seconds" integer default 0,
  "created_at" text,
  "category_id" text,
  "import_key" text,
  "location" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists items_user_idx on items(user_id);

-- ----------------------------------------------------------------------
create table if not exists materials (
  "id" text,
  "class_id" text references classes("id") on delete cascade,
  "category" text,
  "title" text,
  "kind" text,
  "url" text,
  "filename" text,
  "stored_name" text,
  "mimetype" text,
  "size" integer,
  "extracted_text" text,
  "created_at" text,
  "item_id" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists materials_user_idx on materials(user_id);

-- ----------------------------------------------------------------------
create table if not exists note_folders (
  "id" text,
  "class_id" text not null references classes("id") on delete cascade,
  "name" text,
  "created_at" text,
  "parent_id" text,
  "kind" text default 'custom',
  "sort_order" integer default 0,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists note_folders_user_idx on note_folders(user_id);

-- ----------------------------------------------------------------------
create table if not exists schedule_entries (
  "id" text,
  "class_id" text not null references classes("id") on delete cascade,
  "day" integer,
  "start" text,
  "end" text,
  "location" text,
  "kind" text default 'lecture',
  "section" text,
  "start_date" text,
  "end_date" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists schedule_entries_user_idx on schedule_entries(user_id);

-- ----------------------------------------------------------------------
create table if not exists syllabus_imports (
  "id" text,
  "class_id" text references classes("id") on delete set null,
  "filename" text,
  "stored_name" text,
  "mimetype" text,
  "draft" text,
  "official" text,
  "model" text,
  "input_tokens" integer default 0,
  "output_tokens" integer default 0,
  "status" text default 'review',
  "created_at" text,
  "imported_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists syllabus_imports_user_idx on syllabus_imports(user_id);

-- ----------------------------------------------------------------------
create table if not exists syllabus_topics (
  "id" text,
  "class_id" text not null references classes("id") on delete cascade,
  "title" text,
  "done" integer default 0,
  "sort_order" integer,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists syllabus_topics_user_idx on syllabus_topics(user_id);

-- ----------------------------------------------------------------------
create table if not exists sync_links (
  "id" text,
  "account_id" text not null references calendar_accounts("id") on delete cascade,
  "local_kind" text,
  "local_id" text,
  "external_id" text,
  "etag" text,
  "local_hash" text,
  "remote_hash" text,
  "remote_updated" text,
  "last_synced" text,
  "state" text default 'clean',
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id"),
  unique ("account_id", "external_id"),
  unique ("account_id", "local_kind", "local_id")
);
create index if not exists sync_links_user_idx on sync_links(user_id);
create index if not exists sync_links_by_local on sync_links("local_kind", "local_id");

-- ----------------------------------------------------------------------
create table if not exists headstarts (
  "id" text,
  "item_id" text not null references items("id") on delete cascade,
  "kind" text not null,
  "content" text,
  "status" text default 'draft',
  "instructions" text,
  "created_at" text,
  "updated_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id"),
  unique ("item_id", "kind")
);
create index if not exists headstarts_user_idx on headstarts(user_id);

-- ----------------------------------------------------------------------
create table if not exists item_files (
  "id" text,
  "item_id" text not null references items("id") on delete cascade,
  "material_id" text not null references materials("id") on delete cascade,
  "created_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id"),
  unique ("item_id", "material_id")
);
create index if not exists item_files_user_idx on item_files(user_id);
create index if not exists item_files_by_material on item_files("material_id");

-- ----------------------------------------------------------------------
create table if not exists notes (
  "id" text,
  "class_id" text references classes("id") on delete cascade,
  "title" text,
  "folder_id" text,
  "text" text,
  "linked_item_id" text references items("id") on delete set null,
  "updated_at" text,
  "created_at" text,
  "pinned" integer default 0,
  "starred" integer default 0,
  "sort_order" integer default 0,
  "deleted_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists notes_user_idx on notes(user_id);

-- ----------------------------------------------------------------------
create table if not exists quizzes (
  "id" text,
  "class_id" text references classes("id") on delete cascade,
  "item_id" text references items("id") on delete set null,
  "title" text,
  "kind" text default 'quiz',
  "difficulty" text default 'mixed',
  "source" text default 'manual',
  "created_at" text,
  "updated_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists quizzes_user_idx on quizzes(user_id);

-- ----------------------------------------------------------------------
create table if not exists rubrics (
  "id" text,
  "material_id" text not null references materials("id") on delete cascade,
  "item_id" text references items("id") on delete set null,
  "criteria" text,
  "total_points" double precision,
  "created_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id"),
  unique ("material_id")
);
create index if not exists rubrics_user_idx on rubrics(user_id);

-- ----------------------------------------------------------------------
create table if not exists subtasks (
  "id" text,
  "item_id" text not null references items("id") on delete cascade,
  "title" text,
  "done" integer default 0,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists subtasks_user_idx on subtasks(user_id);

-- ----------------------------------------------------------------------
create table if not exists flashcard_decks (
  "id" text,
  "class_id" text references classes("id") on delete cascade,
  "name" text,
  "description" text,
  "source_note_id" text references notes("id") on delete set null,
  "source_material_id" text references materials("id") on delete set null,
  "created_at" text,
  "updated_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists flashcard_decks_user_idx on flashcard_decks(user_id);

-- ----------------------------------------------------------------------
create table if not exists headstart_sources (
  "id" text,
  "headstart_id" text references headstarts("id") on delete cascade,
  "material_id" text references materials("id") on delete cascade,
  "note_id" text references notes("id") on delete cascade,
  "folder_id" text references note_folders("id") on delete cascade,
  "syllabus_id" text references syllabus_topics("id") on delete cascade,
  "created_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists headstart_sources_user_idx on headstart_sources(user_id);

-- ----------------------------------------------------------------------
create table if not exists note_links (
  "id" text,
  "note_id" text not null references notes("id") on delete cascade,
  "item_id" text references items("id") on delete cascade,
  "file_id" text references materials("id") on delete cascade,
  "event_id" text references events("id") on delete cascade,
  "schedule_entry_id" text references schedule_entries("id") on delete cascade,
  "target_note_id" text references notes("id") on delete cascade,
  "label" text default '',
  "created_at" text,
  "headstart_id" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists note_links_user_idx on note_links(user_id);

-- ----------------------------------------------------------------------
create table if not exists note_versions (
  "id" text,
  "note_id" text not null references notes("id") on delete cascade,
  "title" text,
  "text" text,
  "created_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists note_versions_user_idx on note_versions(user_id);

-- ----------------------------------------------------------------------
create table if not exists quiz_attempts (
  "id" text,
  "quiz_id" text not null references quizzes("id") on delete cascade,
  "responses" text,
  "score" double precision,
  "correct_count" integer default 0,
  "total_count" integer default 0,
  "started_at" text,
  "completed_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists quiz_attempts_user_idx on quiz_attempts(user_id);

-- ----------------------------------------------------------------------
create table if not exists quiz_questions (
  "id" text,
  "quiz_id" text not null references quizzes("id") on delete cascade,
  "kind" text default 'multiple_choice',
  "prompt" text,
  "choices" text,
  "answer" text,
  "explanation" text,
  "sort_order" integer default 0,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists quiz_questions_user_idx on quiz_questions(user_id);

-- ----------------------------------------------------------------------
create table if not exists flashcards (
  "id" text,
  "deck_id" text not null references flashcard_decks("id") on delete cascade,
  "front" text,
  "back" text,
  "kind" text default 'term',
  "ease" double precision default 2.5,
  "interval_days" integer default 0,
  "repetitions" integer default 0,
  "lapses" integer default 0,
  "due_date" text,
  "last_reviewed_at" text,
  "suspended" integer default 0,
  "sort_order" integer default 0,
  "created_at" text,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  primary key ("id")
);
create index if not exists flashcards_user_idx on flashcards(user_id);

-- ----------------------------------------------------------------------
-- Owner-only Row Level Security on every table, via the helper the existing
-- cloud schema already uses (002_rls.sql). Forced, with WITH CHECK on updates so
-- a row cannot be handed to someone else.
do $$
declare t text;
begin
  foreach t in array array[
    'ai_usage',
    'app_settings',
    'calendar_accounts',
    'classes',
    'term_settings',
    'calendar_imports',
    'events',
    'grade_categories',
    'items',
    'materials',
    'note_folders',
    'schedule_entries',
    'syllabus_imports',
    'syllabus_topics',
    'sync_links',
    'headstarts',
    'item_files',
    'notes',
    'quizzes',
    'rubrics',
    'subtasks',
    'flashcard_decks',
    'headstart_sources',
    'note_links',
    'note_versions',
    'quiz_attempts',
    'quiz_questions',
    'flashcards'
  ] loop
    perform apply_owner_rls(t);
  end loop;
end $$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on all tables in schema public from anon;

commit;

-- Every row below must show rls_enabled = true.
select c.relname as table_name, c.relrowsecurity as rls_enabled
from pg_class c join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and c.relkind = 'r' order by c.relname;
